// Mocks generated by Mockito 5.4.5 from annotations
// in h_r_optimistic_mobile/test/unit/features/onsite/domain/usecases/get_onsite_requests_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i5;
import 'package:h_r_optimistic_mobile/features/onsite/domain/entities/onsite_entities.dart'
    as _i2;
import 'package:h_r_optimistic_mobile/features/onsite/domain/repositories/onsite_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOnsiteRequest_0 extends _i1.SmartFake implements _i2.OnsiteRequest {
  _FakeOnsiteRequest_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOnsiteStats_1 extends _i1.SmartFake implements _i2.OnsiteStats {
  _FakeOnsiteStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OnsiteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnsiteRepository extends _i1.Mock implements _i3.OnsiteRepository {
  @override
  _i4.Future<List<_i2.OnsiteRequest>> getOnsiteRequests(String? employeeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnsiteRequests,
          [employeeId],
        ),
        returnValue:
            _i4.Future<List<_i2.OnsiteRequest>>.value(<_i2.OnsiteRequest>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.OnsiteRequest>>.value(<_i2.OnsiteRequest>[]),
      ) as _i4.Future<List<_i2.OnsiteRequest>>);

  @override
  _i4.Future<_i2.OnsiteRequest> createOnsiteRequest({
    required String? employeeId,
    required DateTime? startDate,
    required DateTime? endDate,
    required _i5.TimeOfDay? startTime,
    required _i5.TimeOfDay? endTime,
    required _i2.OnsiteType? type,
    required String? location,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOnsiteRequest,
          [],
          {
            #employeeId: employeeId,
            #startDate: startDate,
            #endDate: endDate,
            #startTime: startTime,
            #endTime: endTime,
            #type: type,
            #location: location,
            #reason: reason,
          },
        ),
        returnValue: _i4.Future<_i2.OnsiteRequest>.value(_FakeOnsiteRequest_0(
          this,
          Invocation.method(
            #createOnsiteRequest,
            [],
            {
              #employeeId: employeeId,
              #startDate: startDate,
              #endDate: endDate,
              #startTime: startTime,
              #endTime: endTime,
              #type: type,
              #location: location,
              #reason: reason,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.OnsiteRequest>.value(_FakeOnsiteRequest_0(
          this,
          Invocation.method(
            #createOnsiteRequest,
            [],
            {
              #employeeId: employeeId,
              #startDate: startDate,
              #endDate: endDate,
              #startTime: startTime,
              #endTime: endTime,
              #type: type,
              #location: location,
              #reason: reason,
            },
          ),
        )),
      ) as _i4.Future<_i2.OnsiteRequest>);

  @override
  _i4.Future<_i2.OnsiteRequest> updateOnsiteRequest({
    required String? requestId,
    required _i2.OnsiteStatus? status,
    String? approverNote,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOnsiteRequest,
          [],
          {
            #requestId: requestId,
            #status: status,
            #approverNote: approverNote,
          },
        ),
        returnValue: _i4.Future<_i2.OnsiteRequest>.value(_FakeOnsiteRequest_0(
          this,
          Invocation.method(
            #updateOnsiteRequest,
            [],
            {
              #requestId: requestId,
              #status: status,
              #approverNote: approverNote,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.OnsiteRequest>.value(_FakeOnsiteRequest_0(
          this,
          Invocation.method(
            #updateOnsiteRequest,
            [],
            {
              #requestId: requestId,
              #status: status,
              #approverNote: approverNote,
            },
          ),
        )),
      ) as _i4.Future<_i2.OnsiteRequest>);

  @override
  _i4.Future<_i2.OnsiteRequest> cancelOnsiteRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOnsiteRequest,
          [requestId],
        ),
        returnValue: _i4.Future<_i2.OnsiteRequest>.value(_FakeOnsiteRequest_0(
          this,
          Invocation.method(
            #cancelOnsiteRequest,
            [requestId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.OnsiteRequest>.value(_FakeOnsiteRequest_0(
          this,
          Invocation.method(
            #cancelOnsiteRequest,
            [requestId],
          ),
        )),
      ) as _i4.Future<_i2.OnsiteRequest>);

  @override
  _i4.Future<void> deleteOnsiteRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOnsiteRequest,
          [requestId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.OnsiteRequest>> getPendingOnsiteRequests({
    required String? employeeId,
    bool? isApprover = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingOnsiteRequests,
          [],
          {
            #employeeId: employeeId,
            #isApprover: isApprover,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.OnsiteRequest>>.value(<_i2.OnsiteRequest>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.OnsiteRequest>>.value(<_i2.OnsiteRequest>[]),
      ) as _i4.Future<List<_i2.OnsiteRequest>>);

  @override
  _i4.Future<_i2.OnsiteStats> getOnsiteStats({
    required String? employeeId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnsiteStats,
          [],
          {
            #employeeId: employeeId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i4.Future<_i2.OnsiteStats>.value(_FakeOnsiteStats_1(
          this,
          Invocation.method(
            #getOnsiteStats,
            [],
            {
              #employeeId: employeeId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.OnsiteStats>.value(_FakeOnsiteStats_1(
          this,
          Invocation.method(
            #getOnsiteStats,
            [],
            {
              #employeeId: employeeId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.OnsiteStats>);
}
